# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a3c2360d247cea56a3a6309fd23a621b968242b6ce87972ec469b17759531bfc6870429230db365ebe861805512e6006a8c1e929670600588a0f91574b2ff31

test:
  secret_key_base: f8188bd6b6bff7bb3aef04607f95c69c68c2bc2a5cf3c54a83b277ee93a983684d86c5a12f060d1410e5ff13131d0526cf945337efc8a8141f229464a4cb1a4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
